#!/usr/bin/env bash

ENVIRONMENT_REPO="https://github.com/pliljenberg/environment.git"
ENVIRONMENT_PATH="tools/environment"

if ! type -p git; then
  echo "'git' command not found. Please install git first."
  exit 1
fi

cd "$HOME"
mkdir -p $ENVIRONMENT_PATH
git clone $ENVIRONMENT_REPO $ENVIRONMENT_PATH

echo "Cloned to ${ENVIRONMENT_PATH}"
